// Auto-generated by `flutter create .` as a counter-app template, then
// adapted 2026-09-12 to this app's actual root widget (AureusAiApp) — the
// original template referenced a nonexistent `MyApp` counter widget.

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:aureus_ai/main.dart';

void main() {
  testWidgets('App builds without crashing', (WidgetTester tester) async {
    await tester.pumpWidget(const AureusAiApp());
    await tester.pump();
    expect(find.byType(MaterialApp), findsOneWidget);
  });
}
